---
title: "RootScanR Package Report, by pkgnet"
output: 
    rmarkdown::html_vignette:
        toc: true
vignette: >
    %\VignetteIndexEntry{ RootScanR Package Report, by pkgnet }
    %\VignetteEngine{knitr::rmarkdown}
    %\VignetteEncoding{UTF-8}
---

This report on **RootScanR** is generated by [**pkgnet**](https://uptakeopensource.github.io/pkgnet/), an R package for analyzing other R packages through the lens of [network theory](https://en.wikipedia.org/wiki/Network_theory). 

```{r setup, include=FALSE}
library(pkgnet)

knitr::opts_chunk$set(
    echo = FALSE
    , warning=FALSE
    , message=FALSE
    , out.width='100%'
)
pkgnet:::silence_logger()

# Function report first, dependency report below it.
reporters <- list(FunctionReporter$new(), DependencyReporter$new())

reporters <- lapply(
          X = reporters
          , FUN = function(reporter){
              # set_package() runs static analysis (cyclocomp, lintr, etc.)
              # which prints progress bars / messages directly to the console.
              # Swallow that output so it doesn't end up in the rendered report.
              invisible(utils::capture.output(
                suppressMessages(suppressWarnings(
                  reporter$set_package(pkg_name = "RootScanR")
                ))
                , type = "message"
              ))
              return(reporter)
          }
      )

```

```{r warning=FALSE}
reportSections <- lapply(reporters, function(reporter) {
  report_env <- list2env(list(reporter = reporter))
  suppressMessages(suppressWarnings(
    knitr::knit_child(
      reporter$report_markdown_path
      , envir = report_env
      , quiet = TRUE
    )
  ))
})

```

```{r results="asis"}
cat(paste0(paste(reportSections, collapse = '\n')))
```

---

```{r results="asis"}
cat(sprintf("<sup>This report built with **pkgnet v%s**.</sup>", packageVersion('pkgnet')))
```

<sup>[**pkgnet**](https://uptakeopensource.github.io/pkgnet/) is an open-source R package, copyright &copy; 2017-2019 Uptake, made available under the 3-Clause BSD License.</sup>

```{r echo = FALSE}
pkgnet:::unsilence_logger()
```
